#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original2
echo "
listen 27172-lb-01
        bind 0:80
        mode http
        stats enable
        balance roundrobin
        option httpclose
        option forwardfor
        server 27172-web-01 35.172.136.66 check port 80
        server 27172-web-02 34.232.72.61 check port 80
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
